import type { Metadata } from "next"
import css from "./global.module.scss"
import ToasterContext from "@/lib/Toaster"
import BodyHeight from "@/func/BodyHeight"
import Sessioncontext from "@/lib/Sessioncontext"
import Reduxprovider from "@/lib/redux/Reduxprovider"
import ReduxData from "@/func/ReduxData"

export const metadata: Metadata = {
  title: "ShopEase",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <body className={css.home}>
        <Sessioncontext>
          <Reduxprovider>
              <BodyHeight />
              <ToasterContext />
              <ReduxData />
              {children}
          </Reduxprovider>
        </Sessioncontext>
      </body>
    </html>
  )
}
